// @ts-nocheck
import { useRef, useState } from 'react';
import { inspectIroningBacklight, inspectPatternPhoto, rectifyImageData } from '../core/engine';

const cornerNames=['左上','右上','右下','左下'];
function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=reject;img.src=url})}

export default function InspectionPanel({pattern,mode,onToast,onMarkCompleted}){
  const inputRef=useRef(null), canvasRef=useRef(null), resultRef=useRef(null), baseRef=useRef(null), pointsRef=useRef([]);
  const [pointCount,setPointCount]=useState(0),[stats,setStats]=useState(null),[issues,setIssues]=useState([]),[threshold,setThreshold]=useState(13),[correctIndexes,setCorrectIndexes]=useState([]);
  const isPhoto=mode==='photo';

  async function onFile(ev){const f=ev.target.files?.[0];if(!f)return;try{const img=await loadImage(f);const canvas=canvasRef.current;const scale=Math.min(760/img.naturalWidth,560/img.naturalHeight,1);canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,canvas.width,canvas.height);baseRef.current=ctx.getImageData(0,0,canvas.width,canvas.height);pointsRef.current=[];setPointCount(0);setStats(null);setIssues([]);setCorrectIndexes([])}catch(e){onToast('图片读取失败','bad')}}
  function redraw(){const canvas=canvasRef.current,base=baseRef.current;if(!base)return;const ctx=canvas.getContext('2d');ctx.putImageData(base,0,0);const pts=pointsRef.current;ctx.strokeStyle='#e14f3e';ctx.fillStyle='#e14f3e';ctx.lineWidth=2;ctx.font='bold 14px system-ui';if(pts.length>1){ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.stroke()}pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(String(i+1),p.x-4,p.y+5);ctx.fillStyle='#e14f3e'})}
  function clickCanvas(ev){if(!baseRef.current||pointsRef.current.length>=4)return;const c=canvasRef.current,r=c.getBoundingClientRect();pointsRef.current.push({x:(ev.clientX-r.left)*c.width/r.width,y:(ev.clientY-r.top)*c.height/r.height});setPointCount(pointsRef.current.length);redraw()}
  function reset(){pointsRef.current=[];setPointCount(0);setStats(null);setIssues([]);setCorrectIndexes([]);redraw()}
  function overlay(canvas,results){const ctx=canvas.getContext('2d'),cw=canvas.width/pattern.width,ch=canvas.height/pattern.height;ctx.lineWidth=Math.max(1,Math.min(cw,ch)*.12);for(const r of results){let color=null;if(isPhoto){if(r.status==='wrong')color='#e33d2e';else if(r.status==='uncertain')color='#e4a21b';else if(r.status==='missing')color='#6b55c5'}else{if(r.status==='under')color='#e4a21b';else if(r.status==='over')color='#e33d2e'}if(!color)continue;ctx.strokeStyle=color;ctx.strokeRect(r.x*cw+1,r.y*ch+1,cw-2,ch-2)}}
  function run(){if(!pattern)return onToast('先创建图纸','bad');if(!baseRef.current)return onToast('先上传照片','bad');if(pointsRef.current.length!==4)return onToast('先按顺序点完四个角','bad');try{const cell=Math.max(7,Math.min(14,Math.floor(900/Math.max(pattern.width,pattern.height))));const rect=rectifyImageData(baseRef.current,pointsRef.current,pattern.width*cell,pattern.height*cell);const out=resultRef.current;out.width=rect.width;out.height=rect.height;out.getContext('2d').putImageData(new ImageData(rect.data,rect.width,rect.height),0,0);if(isPhoto){const r=inspectPatternPhoto(pattern,rect,{deltaEThreshold:Number(threshold)||13});overlay(out,r.results);setStats({a:r.correct,b:r.wrong,c:r.uncertain,d:r.missing,total:r.total,gain:r.calibration?.gain});setIssues(r.results.filter(x=>x.status!=='ok').slice(0,80));setCorrectIndexes(r.results.filter(x=>x.status==='ok').map(x=>x.index));onToast('验豆完成：红=错色，黄=疑似，紫=疑似漏豆','ok')}else{const r=inspectIroningBacklight(pattern,rect,{});overlay(out,r.results);setStats({score:r.score,a:r.normal,b:r.under,c:r.over,total:r.total});setIssues(r.results.filter(x=>x.status!=='normal').slice(0,80));onToast('熨烫均匀度检测完成','ok')}}catch(e){console.error(e);onToast('检测失败，请检查四角顺序','bad')}}
  const hint=pointCount<4?`请点 ${cornerNames[pointCount]}（第 ${pointCount+1}/4 个角）`:'四角已完成，可以开始检测';
  return <div className="inspection-grid"><div className="card"><div className="card-hd"><div><h2>{isPhoto?'拍照验豆':'熨烫均匀度检测'}</h2><p>{isPhoto?'实物板 vs 当前图纸':'建议使用背光照片'}</p></div><span className={isPhoto?'badge':'badge warn'}>{isPhoto?'POC 可用':'实验'}</span></div><div className="card-bd"><div className="toolbar"><label className="filebtn">上传照片<input ref={inputRef} type="file" accept="image/*" onChange={onFile}/></label><button onClick={reset}>重选四角</button>{isPhoto&&<label className="inline-field">容差 ΔE <input type="number" min="4" max="40" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label>}<button className="primary" onClick={run}>开始检测</button></div><div className="hint">{hint}</div></div><div className="calibration"><canvas ref={canvasRef} width="720" height="440" onClick={clickCanvas}/></div></div>
  <div className="card"><div className="card-hd"><h2>检测结果</h2></div><div className="card-bd">{isPhoto?<div className="callout">拍摄尽量正、光线均匀。按 <b>左上 → 右上 → 右下 → 左下</b> 点四角。系统会透视矫正、环形采色，并用多数正确豆自动做轻量光照校准；<b>紫框</b>表示中心与豆环对比过低，疑似漏豆。</div>:<div className="callout">把成品举到白色屏幕或灯前，让孔洞明显透光。本功能只评估表面孔洞/熔融均匀度，<b>不能保证结构强度</b>。</div>}
  {stats&&<><div className="metrics">{!isPhoto&&<div><strong>{stats.score}</strong><span>均匀度分</span></div>}<div><strong>{stats.a}</strong><span>正常</span></div><div><strong>{stats.b}</strong><span>{isPhoto?'明显错色':'疑似熔合不足'}</span></div><div><strong>{stats.c}</strong><span>{isPhoto?'需确认':'疑似过熔'}</span></div>{isPhoto&&<div><strong>{stats.d||0}</strong><span>疑似漏豆</span></div>}</div>{isPhoto&&stats.gain&&<div className="calibration-note">自动光照校准 RGB：{stats.gain.map(x=>x.toFixed(2)).join(' / ')}</div>}{isPhoto&&correctIndexes.length>0&&onMarkCompleted&&<button className="primary inspection-progress-btn" onClick={()=>{onMarkCompleted(correctIndexes);onToast(`已把 ${correctIndexes.length} 个正常格写入施工进度`,'ok')}}>把 {correctIndexes.length} 个正常格标记为已拼</button>}</>}
  <div className="result-canvas"><canvas ref={resultRef}/></div>{issues.length>0&&<div className="table-wrap compact"><table><thead><tr><th>位置</th>{isPhoto&&<><th>应为</th><th>识别</th><th>ΔE</th></>}<th>状态</th></tr></thead><tbody>{issues.map((r,i)=><tr key={i}><td>{r.y+1},{r.x+1}</td>{isPhoto&&<><td>{r.target}</td><td>{r.predicted}</td><td>{r.deltaE.toFixed(1)}</td></>}<td>{isPhoto?(r.status==='wrong'?'错色':r.status==='missing'?'疑似漏豆':'疑似'):(r.status==='under'?'熔合不足':'过熔')}</td></tr>)}</tbody></table></div>}
  </div></div></div>
}
